export const ERROR_CODE = {
  CARD_LOCKED: "CARD_LOCKED",
  CHARGE_AMOUNT_TOO_HIGH: "CHARGE_AMOUNT_TOO_HIGH",
  CARD_LIMIT_EXCEEDED_FOR_STORE: "CARD_LIMIT_EXCEEDED_FOR_STORE",
  BOOKING_DELETE: "BOOKING_DELETE",
  ERROR_VALIDATE_BOOKING: "ERROR_VALIDATE",
};
